apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: my-job
        image: busybox
        command: ['expr', '5', '+', '6']
      restartPolicy: Never
