apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-config: |
    server {
      listen 8080;
      server_name localhost;

      root /var/www/html;
      index index.php index.html index.htm;

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
    }