apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-2
  labels: 
    type: local-1
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp